# Generated by Django 3.0.5 on 2021-11-19 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211119_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=280, validators=[django.core.validators.MaxLengthValidator(280, 'Must be less than 280 characters.')]),
        ),
    ]
