# Generated by Django 3.2.9 on 2021-11-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('billing_street', models.CharField(blank=True, max_length=128)),
                ('billing_suburb', models.CharField(blank=True, max_length=64)),
                ('billing_city', models.CharField(blank=True, max_length=64)),
                ('billing_postcode', models.CharField(blank=True, max_length=8)),
                ('billing_country', models.CharField(blank=True, max_length=64)),
                ('shipping_street', models.CharField(blank=True, max_length=128)),
                ('shipping_suburb', models.CharField(blank=True, max_length=64)),
                ('shipping_city', models.CharField(blank=True, max_length=64)),
                ('shipping_postcode', models.CharField(blank=True, max_length=6)),
                ('shipping_country', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
