# Generated by Django 3.2.9 on 2021-12-01 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_salesitem_salesorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='channel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.saleschannel'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='reference',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
