# Generated by Django 3.2.9 on 2021-12-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20211201_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.saleschannel'),
        ),
    ]
